name: SonarCloud .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyze with SonarCloud
    runs-on: windows-latest

    steps:
      # 1. Descargar el código
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Instalar .NET (ajusta si usas otra versión)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 3. Compilar y analizar con SonarCloud
      #    OJO: trabajamos dentro de la carpeta Parcial_CleanFixed,
      #    que es donde están BadCleanArch.sln y src/
      - name: Build and analyze
        working-directory: Parcial_CleanFixed
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner

          dotnet sonarscanner begin `
            /k:"Saenz10200_ParcialCleanArch" `
            /o:"saenz10200" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.token="${env:SONAR_TOKEN}"

          dotnet restore
          dotnet build --no-incremental

          dotnet sonarscanner end `
            /d:sonar.token="${env:SONAR_TOKEN}"
